COLUMNS:
  Sample code number: float64  
  Clump thickness: float64   
  Uniformity of cell size: float64   
  Uniformity of cell shape: float64    
  Marginaln adhesion: float64    
  Single epithelial cell size: float64   
  Bare nuclei: float64  
  Bland chromatin: float64    
  Normal nucleoli: float64    
  Mitoses: float64    
  class : int64

TARGET_COLUMN:
 name :  Class